### ISSUE TITLE
Containerize

### ISSUE THREAD

**Issue by bscott** [shunfei/aproxy#3]
So, 

I'm trying to get this running in a docker container but to get a account created I must run in the command line using the aproxy cli client. Any suggestions?

**Comment by bscott** [comment]
Is there a way to delete a user, not just add. Looking thru the code, I don't see the method.

**Comment by QLeelulu** [comment]
https://github.com/shunfei/aproxy/blob/master/module/setting/user.go#L93

It can delete user.
I will check the release tarball file.

I don't tested docker, sorry for that i can't give any suggestions.

**Comment by QLeelulu** [comment]
![image](https://cloud.githubusercontent.com/assets/570889/10475779/d1018408-7279-11e5-87b9-c784c7dca865.png)

You can delete user by click the `DEL` button.
