### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by hanye1310370** [shunfei/aproxy#4]
这个 使用aproxy对cronsun做域名限制访问，cronsun是基于ip地址访问，在aproxy里面添加限制访问之后，通过域名做访问，还需要在nginx上面做代理吗。还是只在aproxy写规则即可

**Comment by QLeelulu** [comment]
```
server {
  listen 80;
  server_name pri.domain.com *.pri.domain.com;

  location / {
    include proxy.conf;
    # pass to aproxy
    proxy_pass http://127.0.0.1:8098;
  }

}
```

不用改nginx配置，但是注意文档中提到的 nginx 配置的 `*.pri.domain.com` 这个，这个就是所有的 `*.pri.domain.com` 下的子域名都通过aproxy来代理了，所以你的aproxy里面的规则cronsun的域名应该是类似 `cronsun.pri.domain.com` 这样。

**Comment by hanye1310370** [comment]
恩恩  我是这样配置的 但是访问 一直是加载 
![default](https://user-images.githubusercontent.com/12537321/33416318-ebddca44-d5d6-11e7-927c-08c46ba9ba5b.png)

**Comment by hanye1310370** [comment]
cronsun.aproxy.domain.com/ui/  访问这个 一直提示报错

**Comment by hanye1310370** [comment]
![default](https://user-images.githubusercontent.com/12537321/33416371-2931d85e-d5d7-11e7-908a-3103e87153f3.png)

**Comment by QLeelulu** [comment]
UpStream 那里不要加上ui，填 http://127.0.0.1:7079 就好

**Comment by hanye1310370** [comment]
谢谢
